### ISSUE TITLE
Violation of MIT license of react-photo-gallery

### ISSUE THREAD

**Issue by neptunian** [anediaz/react-photo-container#2]
If you read my license at https://github.com/neptunian/react-photo-gallery you are violating it.  You cannot copy my entire codebase and give no credit whatsoever and modify the license.  I can file a complaint to github unless you close the repo on here and NPM or modify your license to give credit to where its due.  Thanks.

**Comment by anediaz** [comment]
I'm so so sorry!
I'll modify my license to give give credit.
All my apologies!

**Comment by anediaz** [comment]
Hello,
Could you please tell me what I am supposed to write in my repo's license
file?
Should I keep your repo's license 'as it' and add a paragraph at the end
mentioning me?

I apologize, I didn't want to do it wrong :-(

2017-02-26 21:57 GMT+01:00 Sandra <notifications@github.com>:

**Comment by neptunian** [comment]
Well if you read the license there should be a note giving credit to the source in your license and it'd be nice if there was also some reference in your repo docs.  Thanks!

**Comment by neptunian** [comment]
btw the latest release addresses some of your issues https://github.com/neptunian/react-photo-gallery/releases/tag/5.0.0

Unfortunately i wasn't able to use your changes because i wanted to remove the cols (images per row) from the Gallery and let the user handle it through a prop.  I also wanted to totally remove the Lightbox from the gallery.

**Comment by anediaz** [comment]
I've modified LICENSE as well as README. Let me know if it's OK for you.

I've taken a look to your component's last modifications and they're almost similar of what I've done in mine.
Only the prop 'col' differs : I wanted to give the possibility to choose the cols (images per row) for different screen sizes, and let user handle it through a prop called 'custom'.

I hesitate to remove my repo and using yours instead (as in the beginning) as differences between both are minimum.

**Comment by neptunian** [comment]
Actually the lightbox is no longer used inside of Gallery.js so its quite different. The gallery is stateless now.  Also the user can indeed choose the cols based on the screensize if you look at the new code.

**Comment by neptunian** [comment]
And yes that is sufficient and I really appreciate it!  thank you!
